### ISSUE TITLE
"An app update is required"

### ISSUE THREAD

**Issue by Prog72** [MattTW/BlinkMonitorProtocol#81]
Is anyone getting this message when attempting to log in? Presumably the API has been deprecated.

**Comment by derolli1976** [comment]
Looks like it is broken.
https://github.com/fronzbot/blinkpy/issues/1114

**Comment by Prog72** [comment]
Thanks, I've got it working again using the info in that thread.

**Comment by RockyBee** [comment]
@Prog72 : What did you have to change for a request (e.g. to retrieve a preview image) after you got the authentication?

**Comment by yphoenix** [comment]
@Prog72 do you have a patch that fixes things?

**Comment by Prog72** [comment]
> [@Prog72](https://github.com/Prog72) do you have a patch that fixes things?

Here's what I'm using. I'm no expert so hopefully it makes sense!

POST https://api.oauth.blink.com/oauth/token

**Headers**

**content-type**  application/x-www-form-urlencoded
**hardware_id** _unique ID_

**Body*

**username** _username_
**password** _password_
**grant_type** password
**client_id** android
**scope** client

I then got a code sent to my phone by SMS which is used in the following.

POST https://api.oauth.blink.com/oauth/token

**Headers**

**2fa-code** _6 digit OTP_
**content-type** application/x-www-form-urlencoded

**Body**

**hardware_id** _unique ID_
**username** _username_
**password** _password_
**grant_type** password
**client_id** android
**scope** client

This will return an access token which is required for any subsequent requests. The URLs for arming, disarming etc. appear to be the same but the header has changed from token-auth to the following.

**Authorization** Bearer _access token_

**Comment by will-k-2** [comment]
@Prog72  Are you able to provide your full code for this omitting personal information obviously. I tried to edit mine but couldn't get it working.

**Comment by yphoenix** [comment]
I implemented the new auth system for the Blink-for-home homebridge plugin, you are welcome to look there: https://github.com/yphoenix/homebridge-blink-for-home. This alternative repo also implemented the change: https://github.com/Flomentum-Solutions/homebridge-blink-for-home-new

**Comment by will-k-2** [comment]
Did anyone manage to get working on PowerShell tried looking at the suggestions but still not able to get working any help would be appreciated.

**Comment by will-k-2** [comment]
This has been fixed: https://github.com/nayrk/Blink/pull/38 by https://github.com/tpgal
